sudo: required
language: groovy
jdk:
  - openjdk7
  - oraclejdk7
services:
- postgresql
branches:
  only:
  - master
before_install:
  - sudo apt-get install unzip
  - sudo apt-get install zip
  - sudo apt-get install sed
  - curl -s "https://get.sdkman.io" | bash
  - export SDKMAN_DIR="$HOME/.sdkman" 
  - $HOME/.sdkman/bin/sdkman-init.sh
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install grails 2.0.3
  - sdk default grails 2.0.3
script: grails test-app --stacktrace
deploy:
  provider: heroku
  api_key:
    secure: TkqBeShQNz8cafBG5b85nwJnxPawFm/PnoIkHvDfOuxD9Lqt6MImV9ydB5GMe3FiAvjkw8i7xNWSb5NgAkYOyXcvLPPE71DVJ6kTGytlQa9emsI8Mz7KFYUgZzPOQxeA3UiSckhnOofCcm5R7rodYkPUpXDJnAJlnLPHn3mNWJmqpKE+bh4LCxyi/wfMID6W1F+6BJ5HEb9qXQl1Wny+f/ZIf0p13jw7YNrfjVQgQh9XhpUNLaDih2gkaAi7srSvJvi1hLorl+NFU1Wj2kE+vk9wSV133LYLFymUyqDaQZScL1eiR9nIexKTZ6FtNp+YOXQ2iMnqDOO3vjBMBYypzkAbLNxSuwIIOhszRg74eLuTStTzyGnNZ64Ao9JAzHwirNRj/hCrerLyUHebGY8jc65E28y/CL63zf6wMVT5z1NeaSV/pDXOVQPVu5iX8bh5qlTT0262/IjCgTf9ogS6+0bKPqWpPMuvl0ZuJnu4PSpiIFkhbSRIxjL7vuGGKoibLQFSZBeeHv4oIKVo+MeKMTEcvlW7mH+50LLk9jVbLv37zfBTyvXhDVDCB2IpSey8uRaltYdiOGU09YGdYt8OPInzy+SRX+YBaRsFJOyaM1cdzEm5zkNZ4hf0fZ2NcL5nuc9O7FPBwnj2sB4lFqzNVKy2ryx0tzgCN1HMvRMGHXU=
  app: sart-test
  on:
    repo: biniama/sart
